# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/saszombie/Coding/OOProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/saszombie/Coding/OOProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saszombie/Coding/OOProject/CMakeFiles /home/saszombie/Coding/OOProject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saszombie/Coding/OOProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

include/Animation.o: include/Animation.cpp.o
.PHONY : include/Animation.o

# target to build an object file
include/Animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Animation.cpp.o
.PHONY : include/Animation.cpp.o

include/Animation.i: include/Animation.cpp.i
.PHONY : include/Animation.i

# target to preprocess a source file
include/Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Animation.cpp.i
.PHONY : include/Animation.cpp.i

include/Animation.s: include/Animation.cpp.s
.PHONY : include/Animation.s

# target to generate assembly for a file
include/Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Animation.cpp.s
.PHONY : include/Animation.cpp.s

include/Character.o: include/Character.cpp.o
.PHONY : include/Character.o

# target to build an object file
include/Character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Character.cpp.o
.PHONY : include/Character.cpp.o

include/Character.i: include/Character.cpp.i
.PHONY : include/Character.i

# target to preprocess a source file
include/Character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Character.cpp.i
.PHONY : include/Character.cpp.i

include/Character.s: include/Character.cpp.s
.PHONY : include/Character.s

# target to generate assembly for a file
include/Character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Character.cpp.s
.PHONY : include/Character.cpp.s

include/Knight.o: include/Knight.cpp.o
.PHONY : include/Knight.o

# target to build an object file
include/Knight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Knight.cpp.o
.PHONY : include/Knight.cpp.o

include/Knight.i: include/Knight.cpp.i
.PHONY : include/Knight.i

# target to preprocess a source file
include/Knight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Knight.cpp.i
.PHONY : include/Knight.cpp.i

include/Knight.s: include/Knight.cpp.s
.PHONY : include/Knight.s

# target to generate assembly for a file
include/Knight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Knight.cpp.s
.PHONY : include/Knight.cpp.s

include/Mage.o: include/Mage.cpp.o
.PHONY : include/Mage.o

# target to build an object file
include/Mage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Mage.cpp.o
.PHONY : include/Mage.cpp.o

include/Mage.i: include/Mage.cpp.i
.PHONY : include/Mage.i

# target to preprocess a source file
include/Mage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Mage.cpp.i
.PHONY : include/Mage.cpp.i

include/Mage.s: include/Mage.cpp.s
.PHONY : include/Mage.s

# target to generate assembly for a file
include/Mage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Mage.cpp.s
.PHONY : include/Mage.cpp.s

include/Pugilist.o: include/Pugilist.cpp.o
.PHONY : include/Pugilist.o

# target to build an object file
include/Pugilist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Pugilist.cpp.o
.PHONY : include/Pugilist.cpp.o

include/Pugilist.i: include/Pugilist.cpp.i
.PHONY : include/Pugilist.i

# target to preprocess a source file
include/Pugilist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Pugilist.cpp.i
.PHONY : include/Pugilist.cpp.i

include/Pugilist.s: include/Pugilist.cpp.s
.PHONY : include/Pugilist.s

# target to generate assembly for a file
include/Pugilist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Pugilist.cpp.s
.PHONY : include/Pugilist.cpp.s

include/Weapon.o: include/Weapon.cpp.o
.PHONY : include/Weapon.o

# target to build an object file
include/Weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Weapon.cpp.o
.PHONY : include/Weapon.cpp.o

include/Weapon.i: include/Weapon.cpp.i
.PHONY : include/Weapon.i

# target to preprocess a source file
include/Weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Weapon.cpp.i
.PHONY : include/Weapon.cpp.i

include/Weapon.s: include/Weapon.cpp.s
.PHONY : include/Weapon.s

# target to generate assembly for a file
include/Weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Weapon.cpp.s
.PHONY : include/Weapon.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... include/Animation.o"
	@echo "... include/Animation.i"
	@echo "... include/Animation.s"
	@echo "... include/Character.o"
	@echo "... include/Character.i"
	@echo "... include/Character.s"
	@echo "... include/Knight.o"
	@echo "... include/Knight.i"
	@echo "... include/Knight.s"
	@echo "... include/Mage.o"
	@echo "... include/Mage.i"
	@echo "... include/Mage.s"
	@echo "... include/Pugilist.o"
	@echo "... include/Pugilist.i"
	@echo "... include/Pugilist.s"
	@echo "... include/Weapon.o"
	@echo "... include/Weapon.i"
	@echo "... include/Weapon.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

